import test from 'node:test';
import assert from 'node:assert/strict';
import { symlinkSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { portablePath, readBoundedFile, canonicalJson, parseJson } from '../../runtime/engineering-practices/io.mjs';
import { captureSnapshot, assertReceipt } from '../../runtime/engineering-practices/core.mjs';
import { runCommand } from '../../runtime/engineering-practices/runner.mjs';
import { parseArgs, execute } from '../../runtime/engineering-practices/cli.mjs';
import { fixture } from './helpers.mjs';
for (const p of ['../escape','/absolute','C:/drive','a\\b','a//b','a/../b','a/./b','file:stream','CON.txt','aux','foo.','foo ','a\0b','a\nb']) test('rejects unsafe path '+JSON.stringify(p),()=>assert.throws(()=>portablePath(p)));
test('UTF-8 JSON rejects invalid bytes',()=>assert.throws(()=>parseJson(Buffer.from([0xff]))));
test('nonfinite values rejected',()=>assert.throws(()=>canonicalJson({value:Infinity})));
test('deep JSON rejected',()=>{let x={};for(let i=0;i<66;i++)x={x};assert.throws(()=>canonicalJson(x));});
test('symlink evidence rejected',t=>{const f=fixture(t);symlinkSync(path.join(f.root,'sample'),path.join(f.root,'linked'),process.platform==='win32'?'junction':'dir');assert.throws(()=>readBoundedFile(f.root,'linked/page.mjs'));});
test('oversized evidence rejected before allocation',t=>{const f=fixture(t);assert.throws(()=>readBoundedFile(f.root,'sample/page.mjs',1));});
test('case-colliding file selection rejected',t=>{const f=fixture(t);assert.throws(()=>captureSnapshot(f.root,['sample/page.mjs','SAMPLE/page.mjs']));});
test('Git internal file snapshot denied',t=>{const f=fixture(t);assert.throws(()=>captureSnapshot(f.root,['.git/config']));});
test('explicit successful command captured',t=>{const f=fixture(t);const r=runCommand(f.root,f.proof.candidate,[process.execPath,'-e','console.log("hello")']);assert.equal(r.status,'PASS');assert.equal(r.stdout.trim(),'hello');assertReceipt(r);});
test('nonzero exit cannot be PASS',t=>{const f=fixture(t);const r=runCommand(f.root,f.proof.candidate,[process.execPath,'-e','process.exit(3)']);assert.equal(r.status,'FAIL');assert.equal(r.exitCode,3);});
test('unavailable executable is SPAWN_ERROR',t=>{const f=fixture(t);const r=runCommand(f.root,f.proof.candidate,['ags-nonexistent-executable-91aef']);assert.equal(r.status,'SPAWN_ERROR');});
test('direct child timeout recorded',t=>{const f=fixture(t);const r=runCommand(f.root,f.proof.candidate,[process.execPath,'-e','setInterval(()=>{},1000)'],{timeoutMs:50});assert.equal(r.status,'TIMED_OUT');});
test('input mutation during command is not PASS',t=>{const f=fixture(t);const r=runCommand(f.root,f.proof.candidate,[process.execPath,'-e','require("node:fs").appendFileSync("sample/page.mjs","// changed\\n")']);assert.equal(r.status,'INPUT_CHANGED');});
test('shell metacharacters remain an argv literal',t=>{const f=fixture(t);const s='$(touch should-not-exist)';const r=runCommand(f.root,f.proof.candidate,[process.execPath,'-e','console.log(process.argv[1])',s]);assert.equal(r.stdout.trim(),s);assert.equal(existsSync(path.join(f.root,'should-not-exist')),false);});
test('invalid timeout rejected before execution',t=>{const f=fixture(t);assert.throws(()=>runCommand(f.root,f.proof.candidate,[process.execPath],{timeoutMs:-1}));});
for(const argv of [[],['unknown'],['catalog','--unknown','x'],['snapshot','--root','x'],['check-plan','--root','x','--root','y','--plan','a'],['run','--root','x','--snapshot','s'],['check-plan','--root','x','--plan','p','--','echo']]) test('CLI rejects invalid argv '+JSON.stringify(argv),()=>assert.throws(()=>parseArgs(argv)));
test('catalog only returns requested module',()=>{const r=execute(['catalog','--module','dependency']);assert.equal(r.value.rules.length,6);assert.ok(r.value.rules.every(x=>x.module==='dependency'));});
test('invalid catalog module rejected',()=>assert.throws(()=>execute(['catalog','--module','not-a-module'])));
test('CLI check-proof uses real input files',t=>{const f=fixture(t);const r=execute(['check-proof','--root',f.root,'--plan','plan.json','--proof','proof.json']);assert.equal(r.exitCode,0);assert.equal(r.value.verdict,'CONSISTENT');});
test('thin skill CLI works outside cwd without node_modules',t=>{const f=fixture(t);const script=new URL('../../skills/test-engineering/scripts/run.mjs',import.meta.url);const r=spawnSync(process.execPath,[fileURLToPath(script),'check-plan','--root',f.root,'--plan','plan.json'],{cwd:f.root,encoding:'utf8'});assert.equal(r.status,0,r.stderr);assert.equal(JSON.parse(r.stdout).verdict,'READY');});
test('CLI failure has a nonzero exit and structured error',()=>{const script=new URL('../../runtime/engineering-practices/cli.mjs',import.meta.url);const r=spawnSync(process.execPath,[fileURLToPath(script),'no-such-command'],{encoding:'utf8'});assert.equal(r.status,2);assert.equal(JSON.parse(r.stderr).status,'ERROR');});
test('nested Node harness environment cannot suppress child tests',t=>{const f=fixture(t);const before=process.env.NODE_TEST_CONTEXT;process.env.NODE_TEST_CONTEXT='child-v8';try {const r=runCommand(f.root,f.proof.candidate,[process.execPath,'--test','sample/page.test.mjs']);assert.equal(r.status,'PASS');assert.match(r.stdout,/PAGE-1/);assert.match(r.stdout,/# tests 1/);assert.doesNotMatch(r.stderr,/skipping running files/);}finally {if(before===undefined)delete process.env.NODE_TEST_CONTEXT;else process.env.NODE_TEST_CONTEXT=before;}});
test('case-folded Git internal path is denied',t=>{const f=fixture(t);assert.throws(()=>captureSnapshot(f.root,['.GIT/config']));});
