import {loadPolicy} from '../../../skills/coordinate-subagents/scripts/model-catalog.mjs';
import {readFileSync} from 'node:fs';
import {digest,seal,resolveV2} from '../../../skills/coordinate-subagents/scripts/model-routing-core.mjs';
// The v2 fixture clock predates newer catalogs; replay its immutable golden snapshot.
const historicalCatalog=JSON.parse(readFileSync(new URL('../semantic-decision/fixtures/v2-golden.json',import.meta.url),'utf8')).environment.catalog;
export const NOW='2026-09-21T12:00:00.000Z';
export const LATER='2026-09-21T12:01:00.000Z';
export const END='2026-09-21T12:04:00.000Z';
export function request(overrides={}) {return {schemaVersion:'2.0.0',binding:{assignmentId:'assignment-1',taskId:'task-1',runId:'run-1',stageId:'stage-1',attemptId:'attempt-1',revision:1,inputDigest:digest('input'),candidateDigest:digest('candidate')},role:'general-implementation',highRisk:false,profile:'balanced',taskTraits:['code-change'],requirements:{inputModalities:['text'],tools:['read'],filesystem:'read',allowedSurfaces:['local-subagent','peer-session','headless'],allowedRuntimeModes:['standard'],allowNestedDelegation:false,requireObservable:[],excludedActors:[],excludedSessions:[],contextMode:'limited'},...overrides};}
export function selection(overrides={}){return {model:'gpt-5.6-terra',resolvedModel:'gpt-5.6-terra',modelOrigin:'openai',servingProvider:'openai',accessPath:'subscription',nativeReasoning:{kind:'enum',value:'high'},runtimeMode:'standard',...overrides};}
export function capability(overrides={},bindingOverrides={}){
 return seal({schemaVersion:'1.0.0',host:'openai-codex',hostVersion:'fixture-1',adapterVersion:'2.5.0',actorId:'actor-1',sessionId:'session-1',instanceId:'instance-1',observedAt:NOW,expiresAt:END,supportedBindings:[{...selection(bindingOverrides),invocationSurface:'local-subagent',observableFields:['model','reasoning','runtimeMode'],aliasResolution:null,possibleFallbacks:[]}],executionCapabilities:{dispatch:true,observe:true,cancel:true,resume:false,filesystem:'write',tools:['read','write'],approvals:'enforced',isolation:'sandbox',inputModalities:['text','image']},source:'host-observation',sourceReference:'fixture:capability',...overrides},'snapshotDigest');
}
export function environment(overrides={}){return {catalog:structuredClone(historicalCatalog),policy:loadPolicy(),capabilities:[capability()],now:NOW,...overrides};}
export function presence(overrides={}){return {host:'openai-codex',sessionId:'session-1',instanceId:'instance-1',state:'online',leaseUntil:END,...overrides};}
export function fixture(overrides={}){const req=request(),env=environment(overrides),decision=resolveV2(req,env);return {req,env,decision};}
export function application(req,decision,overrides={}){return {schemaVersion:'2.0.0',binding:req.binding,decisionDigest:decision.decisionDigest,target:decision.target,dispatched:decision.selected,dispatchedAt:NOW,...overrides};}
export function observation(req,decision,overrides={}){return {binding:req.binding,target:decision.target,decisionDigest:decision.decisionDigest,source:'host-event',reference:'fixture:observation',observedAt:LATER,models:[{resolvedModel:decision.selected.resolvedModel,modelOrigin:decision.selected.modelOrigin}],nativeReasoning:decision.selected.nativeReasoning,runtimeMode:'standard',terminalOutcome:'succeeded',...overrides};}
export function reasons(d){return d.rejectedCandidates.flatMap(c=>c.reasonCodes);}
export const clone=structuredClone;
export function sample(overrides={}){return seal({schemaVersion:'1.0.0',binding:request().binding,host:'openai-codex',hostVersion:'fixture-1',adapterVersion:'2.5.0',resolvedModel:'gpt-5.6-terra',runtimeMode:'standard',scenario:'ko-correction-keep-goal',nativeReasoning:{kind:'enum',value:'high'},tools:['read'],permissionsDigest:digest('read-only'),harnessDigest:digest('harness-1'),testResult:'passed',reworkCount:1,evidenceRejections:0,goalMaintainedAfterCorrection:true,failureKind:null,elapsedMs:1000,waitMs:null,usage:{input:100,output:20,reasoning:null,cacheRead:90,cacheWrite:null,toolCalls:1},cost:{basis:'unknown',amount:null,currency:null,unit:null,sourceReference:null},sourceReference:'fixture:test-harness-not-live-model',observedAt:NOW,...overrides},'recordDigest');}
