import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { onTestFinished, test } from 'vitest';

import { digest, resolveV2 } from '../../../skills/coordinate-subagents/scripts/model-routing-core.mjs';
import { ModelRoutingStore, RoutingObservationSigner } from '../../../skills/coordinate-subagents/scripts/model-routing-store.mjs';
import { ModelRoutingServiceCore, checkApplicationArtifactBinding } from '../../../skills/coordinate-subagents/scripts/model-routing-service-core.mjs';
import { encodePeerAssignment, decodePeerAssignment, acceptPeerAssignment, MODEL_ROUTING_PEER_FEATURE } from '../../../skills/coordinate-subagents/scripts/model-routing-peer.mjs';
import { NOW, LATER, END, request, capability, presence, fixture, application, observation } from './fixtures.mjs';

const signer=new RoutingObservationSigner(Buffer.alloc(32,9));
function receipt(kind,payload){return signer.issue(kind,payload,{issuedAt:NOW,expiresAt:END});}
function memoryDatabase(){const db=new DatabaseSync(':memory:');onTestFinished(()=>db.close());return db;}
function setup(){const db=memoryDatabase();const store=new ModelRoutingStore(db);const f=fixture();store.saveDecision(f.req,f.env,f.decision,NOW);return {db,store,...f};}
function dispatched(store,d){const r=store.reserveDispatch(d,{write:true});store.transition(r.dispatchKey,0,'accepted');store.transition(r.dispatchKey,1,'running',null,NOW);return r.dispatchKey;}

test('additive tables preserve existing records and user_version',()=>{const db=memoryDatabase();db.exec("PRAGMA user_version=24;CREATE TABLE receipts(id TEXT,original TEXT);INSERT INTO receipts VALUES('r','immutable');");new ModelRoutingStore(db);new ModelRoutingStore(db);assert.equal(db.prepare('PRAGMA user_version').get().user_version,24);assert.equal(db.prepare('SELECT original FROM receipts').get().original,'immutable');});
test('capability publication requires signed receipt and matching live instance',()=>{const {store}=setup(),cap=capability(),r=receipt('capability',cap);assert.throws(()=>store.publishCapability({...r,mac:'0'.repeat(64)},signer,presence(),NOW));assert.throws(()=>store.publishCapability(r,signer,presence({instanceId:'other'}),NOW));store.publishCapability(r,signer,presence(),NOW);assert.equal(store.capabilities().length,1);assert.throws(()=>store.publishCapability(r,signer,presence(),NOW),e=>e.code==='RECEIPT_REPLAY');});
test('capability revision cannot regress',()=>{const {store}=setup();const cap=capability({observedAt:LATER});store.publishCapability(receipt('capability',cap),signer,presence(),LATER);assert.throws(()=>store.publishCapability(receipt('capability',capability()),signer,presence(),LATER),e=>e.code==='CAPABILITY_REVISION_REGRESSION');});
test('expired signed receipt denied',()=>{assert.throws(()=>signer.verify(receipt('capability',capability()),'capability',END),e=>e.code==='RECEIPT_EXPIRED');});
test('delivery ACK is neither acceptance nor completion',()=>{const {store,decision}=setup();const r=store.reserveDispatch(decision,{write:true});assert.deepEqual(store.acknowledgeDelivery(r.dispatchKey),{delivered:true,accepted:false,completed:false});assert.equal(store.dispatch(r.dispatchKey).state,'reserved');});
test('duplicate write dispatch has one reservation, no repeated execute entitlement',()=>{const {store,decision}=setup();assert.equal(store.reserveDispatch(decision,{write:true}).duplicate,false);assert.equal(store.reserveDispatch(decision,{write:true}).duplicate,true);});
test('ambiguous write excludes new model, attempt and revision until evidence closes previous',()=>{const {store,decision,req,env}=setup();const key=dispatched(store,decision);store.transition(key,2,'unknown');const req2=structuredClone(req);req2.binding.attemptId='attempt-2';req2.binding.revision=2;const d2=resolveV2(req2,env);assert.throws(()=>store.reserveDispatch(d2,{write:true}),e=>e.code==='AMBIGUOUS_WRITE_ACTIVE');assert.throws(()=>store.transition(key,3,'failed'),e=>e.code==='TERMINAL_EVIDENCE_REQUIRED');store.transition(key,3,'failed','fixture:confirmed-terminal');assert.equal(store.reserveDispatch(d2,{write:true}).duplicate,false);});
test('two connections obey CAS and active-write exclusion',()=>{const dir=mkdtempSync(join(tmpdir(),'ags-two-db-')),file=join(dir,'state.sqlite');const a=new DatabaseSync(file),b=new DatabaseSync(file);onTestFinished(()=>{a.close();b.close();rmSync(dir,{force:true,recursive:true});});const s1=new ModelRoutingStore(a),s2=new ModelRoutingStore(b),{decision,req,env}=fixture();const r=s1.reserveDispatch(decision,{write:true});assert.equal(s2.reserveDispatch(decision,{write:true}).duplicate,true);s1.transition(r.dispatchKey,0,'accepted');assert.throws(()=>s2.transition(r.dispatchKey,0,'accepted'),e=>e.code==='DISPATCH_REVISION_CONFLICT');const req2=structuredClone(req);req2.binding.attemptId='other';assert.throws(()=>s2.reserveDispatch(resolveV2(req2,env),{write:true}));});
test('observation without actual dispatch is rejected',()=>{const {store,req,decision}=setup();assert.throws(()=>store.publishObservation(receipt('observation',observation(req,decision)),signer,LATER),e=>e.code==='DISPATCH_NOT_OBSERVED');});
test('future and cross-task observations are rejected',()=>{const {store,req,decision}=setup();dispatched(store,decision);for(const obs of [observation(req,decision,{observedAt:END}),observation(req,decision,{binding:{...req.binding,taskId:'wrong'}})])assert.throws(()=>store.publishObservation(receipt('observation',obs),signer,LATER));});
test('admitted observation token is single use and final artifact binding checked',()=>{const {store,req,decision}=setup();dispatched(store,decision);const token=store.publishObservation(receipt('observation',observation(req,decision)),signer,LATER);const service=new ModelRoutingServiceCore({store,clock:()=>LATER});const result=service.record({application:application(req,decision),observationToken:token});assert.equal(result.record.status,'matched');assert.equal(result.record.trustedGateSatisfied,false);assert.throws(()=>service.record({application:application(req,decision),observationToken:token}),e=>e.code==='OBSERVATION_TOKEN_UNAVAILABLE');assert.equal(checkApplicationArtifactBinding(result.record,{binding:req.binding,target:decision.target,requiredFields:['model'],store}).trustedExecutionGateSatisfied,false);assert.throws(()=>checkApplicationArtifactBinding(result.record,{binding:req.binding,target:decision.target,requiredFields:['model']}));assert.throws(()=>checkApplicationArtifactBinding(result.record,{binding:{...req.binding,revision:99},target:decision.target}));});
test('failed validation does not consume observation token',()=>{const {store,req,decision}=setup();dispatched(store,decision);const token=store.publishObservation(receipt('observation',observation(req,decision)),signer,LATER);const service=new ModelRoutingServiceCore({store,clock:()=>LATER});assert.throws(()=>service.record({application:application(req,decision,{dispatchedAt:LATER}),observationToken:token}));assert.equal(service.record({application:application(req,decision),observationToken:token}).record.status,'matched');});
test('service calls never accept caller-supplied capabilities and map failures to API errors',()=>{const s=new ModelRoutingServiceCore({clock:()=>NOW});assert.equal(s.call('query_model_catalog',{provider:'openai'}).ok,true);assert.equal(s.call('resolve_model_assignment',request()).data.status,'blocked');assert.equal(s.call('resolve_model_assignment',{...request(),capabilities:[capability()]}).ok,false);const missing=s.call('record_model_application',{application:{}});assert.equal(missing.ok,false);assert.equal(missing.error.details.routingCode,'ROUTING_STORE_UNAVAILABLE');assert.equal(s.call('launch_worker',{}).error.details.routingCode,'UNKNOWN_TOOL');});
test('audit requires authoritative participation history provider',()=>{const {store}=setup();store.publishCapability(receipt('capability',capability()),signer,presence(),NOW);const req=request({role:'independent-audit',highRisk:true});const s=new ModelRoutingServiceCore({store,clock:()=>NOW});assert.throws(()=>s.resolve(req),e=>e.code==='AUDIT_HISTORY_PROVIDER_REQUIRED');const s2=new ModelRoutingServiceCore({store,clock:()=>NOW,historyProvider:()=>({actors:['actor-1'],sessions:[]})});assert.equal(s2.resolve(req).status,'blocked');});
test('peer feature negotiation, delta and receiver target are mandatory',()=>{const {req,decision}=fixture(),body=encodePeerAssignment(req,decision,{delta:'정정: 파일 삭제 없이 조회만 수행한다.'});assert.throws(()=>decodePeerAssignment(body,[]),e=>e.code==='PEER_FEATURE_UNAVAILABLE');assert.equal(decodePeerAssignment(body,[MODEL_ROUTING_PEER_FEATURE]).delta,'정정: 파일 삭제 없이 조회만 수행한다.');assert.throws(()=>encodePeerAssignment(req,decision,{delta:'가'.repeat(2000)}));});
test('peer authorization and post-await presence recheck precede execution',async()=>{const {store,req,env,decision}=setup(),body=encodePeerAssignment(req,decision);const config={features:[MODEL_ROUTING_PEER_FEATURE],target:decision.target,loadAssignment:async()=>({request:req,decision}),environment:{...env,presence:presence(),refresh:async()=>({...env,presence:presence({instanceId:'replaced'})})},authorizeAndConsume:async()=>true,store};await assert.rejects(()=>acceptPeerAssignment(body,config));assert.equal(store.dispatch(digest({binding:req.binding})).state,'not-started');});
test('peer acceptance consumes existing authorization once; replay cannot execute',async()=>{const {store,req,env,decision}=setup(),body=encodePeerAssignment(req,decision);let approvals=0;const current={...env,presence:presence()},config={features:[MODEL_ROUTING_PEER_FEATURE],target:decision.target,loadAssignment:async()=>({request:req,decision}),environment:{...current,refresh:async()=>current},authorizeAndConsume:async()=>{approvals++;return true;},store};assert.equal((await acceptPeerAssignment(body,config)).shouldExecute,true);assert.equal((await acceptPeerAssignment(body,config)).shouldExecute,false);assert.equal(approvals,1);});
