import test from 'node:test';
import assert from 'node:assert/strict';
import { fixture, reviewOptions, clone } from './helpers.mjs';
import { loadPack, selectRules, validateRequest, validateConstraintReport, validateReviewReport, validateBinding, validateCandidate, hashJson, checkBundle, providerResult, adapterError, CsError } from '../../skills/cs-engineering/scripts/core.mjs';
import { reviewForAgs } from '../../skills/cs-engineering/scripts/ags-adapter.mjs';
import { validateSchema } from '../../skills/cs-engineering/scripts/schema-validation.mjs';
const reject=fn=>assert.throws(fn,e=>e instanceof CsError);

test('knowledge pack has ten modules, forty cards, twenty default cards',()=>{const p=loadPack();assert.equal(p.modules.size,10);assert.equal(p.rules.size,40);assert.equal(selectRules(p).length,20);assert.equal(selectRules(p,{allowDraft:true}).length,40);});
test('selection returns only requested domains, without an arbitrary count cap',()=>{const p=loadPack();assert.equal(selectRules(p,{domains:['concurrency','databases']}).length,8);assert.equal(selectRules(p,{domains:['networking']}).length,0);assert.equal(selectRules(p,{domains:['networking'],allowDraft:true}).length,4);});
test('unknown rule or domain is not treated as no-op success',()=>{const p=loadPack();reject(()=>selectRules(p,{domains:['nonexistent']}));reject(()=>selectRules(p,{ruleIds:['UNKNOWN']}));});
test('complete actual reference bundle passes raw-file validation',()=>{const f=fixture(),r=checkBundle(f);assert.equal(r.verdict,'PASS');assert.equal(r.checkedRawFiles,6);assert.equal(r.requiredObligationCount,2);});
test('request and constraints validate normally',()=>{const f=fixture();validateRequest(f.request);assert.equal(validateConstraintReport(f.constraint,f).requiredObligationIds.length,2);});
for(const [name,mut]of[
 ['unknown field',r=>r.unrecognized=true],['duplicate source id',r=>r.sourceRefs.push(clone(r.sourceRefs[0]))],['missing evidence reference',r=>r.operationalFacts[0].evidenceRefs=['BAD']],['snapshot digest drift',r=>r.sourceSnapshotDigest='sha256:'+'0'.repeat(64)],['absolute source path',r=>r.sourceRefs[0].path='/tmp/x'],['duplicate fact',r=>r.operationalFacts.push(clone(r.operationalFacts[0]))]
])test('request rejects '+name,()=>{const f=fixture();mut(f.request);reject(()=>validateRequest(f.request));});
for(const [name,mut]of[
 ['unknown rule',r=>r.selectedRules[0].ruleId='NO-SUCH-RULE'],['wrong rule digest',r=>r.selectedRules[0].ruleDigest='sha256:'+'0'.repeat(64)],['unknown invariant basis',r=>r.invariants[0].basisRefs=['UNKNOWN']],['missing selected rule',r=>r.selectedRules.pop()],['duplicate invariant',r=>r.invariants.push(clone(r.invariants[0]))],['missing required verification',r=>r.verificationObligations.shift()],['required obligation downgraded',r=>r.verificationObligations[0].requirementLevel='advisory'],['duplicate obligation',r=>r.verificationObligations.push(clone(r.verificationObligations[0]))],['wrong pack digest',r=>r.knowledgePackDigest='sha256:'+'a'.repeat(64)],['new request digest',r=>r.requestDigest='sha256:'+'b'.repeat(64)],['fact and assumption collision',r=>r.assumptions.push({id:r.facts[0].id,statement:'guess',verificationPlan:'check source'})],['assumption-only mandatory condition',r=>{r.assumptions.push({id:'A1',statement:'guess',verificationPlan:'check'});r.invariants[0].basisRefs=['A1'];}],['missing rule applicability reason',r=>r.selectedRules[0].applicabilityReason=''],['false not-applicable',r=>r.applicability='not-applicable'],['unknown contract field',r=>r.extra={skip:true}]
])test('constraints reject '+name,()=>{const f=fixture();mut(f.constraint);reject(()=>validateConstraintReport(f.constraint,f));});
test('empty applicable READY report cannot conceal all checks',()=>{const f=fixture();for(const k of ['selectedRules','invariants','verificationObligations','designChoices'])f.constraint[k]=[];reject(()=>validateConstraintReport(f.constraint,f));});
test('genuine non-applicability has a reason and zero applied conditions',()=>{const f=fixture();for(const k of ['selectedRules','invariants','verificationObligations','designChoices'])f.constraint[k]=[];f.constraint.applicability='not-applicable';f.constraint.applicabilityReason='Only prose changes; behavior and contracts are unchanged.';assert.equal(validateConstraintReport(f.constraint,f).requiredObligationIds.length,0);});
test('draft adoption must be explicit in both report and bound policy',()=>{const f=fixture(),rule=f.pack.rules.get('SEC-AUTHORITY-001');f.constraint.selectedRules[0]={ruleId:rule.id,ruleDigest:hashJson(rule),applicabilityReason:'explicitly requested security boundary check'};f.constraint.invariants[0].ruleIds=[rule.id];reject(()=>validateConstraintReport(f.constraint,f));f.constraint.draftUse={allowed:true,basis:'Explicit test adoption only.'};validateConstraintReport(f.constraint,f);f.binding.constraintReportDigest=hashJson(f.constraint);reject(()=>validateBinding(f.binding,f));f.policy.allowDraft=true;f.binding.policyDigest=hashJson(f.policy);validateBinding(f.binding,f);});
for(const [name,mut]of[
 ['task substitution',f=>f.task.objective+=' changed'],['policy downgrade',f=>f.policy.mode='observe'],['policy version drift',f=>f.policy.version='1.1.0'],['missing required ID',f=>f.binding.requiredObligationIds.pop()],['knowledge version mismatch',f=>f.binding.knowledgePackVersion='1.0.0'],['duplicate required ID',f=>f.binding.requiredObligationIds.push(f.binding.requiredObligationIds[0])],['non-ready constraint',f=>f.constraint.verdict='BLOCKED']
])test('binding rejects '+name,()=>{const f=fixture();mut(f);reject(()=>validateBinding(f.binding,f));});
for(const [name,mut]of[
 ['candidate substitution',r=>r.candidateDigest='sha256:'+'0'.repeat(64)],['missing invariant finding',r=>r.findings.pop()],['duplicate invariant finding',r=>r.findings.push({...r.findings[0],id:'F-OTHER'})],['duplicate finding id',r=>r.findings[1].id=r.findings[0].id],['missing obligation result',r=>r.verificationResults.pop()],['duplicate obligation result',r=>r.verificationResults.push(clone(r.verificationResults[0]))],['NOT_RUN claimed PASS',r=>r.verificationResults[0].executionStatus='NOT_RUN'],['EXECUTED UNKNOWN',r=>r.verificationResults[0].result='UNKNOWN'],['stale evidence target',r=>r.evidence[0].targetDigest='sha256:'+'0'.repeat(64)],['wrong verification environment',r=>r.verificationResults[0].environmentRef='mock-only'],['wrong evidence environment',r=>r.evidence[0].environmentRef='old-host'],['wrong verification method',r=>r.verificationResults[0].method='static-review'],['wrong evidence kind',r=>r.evidence[0].kind='static-review'],['missing evidence',r=>r.evidence=[]],['unknown evidence reference',r=>r.findings[0].evidenceRefs=['MISSING']],['empty conclusive finding',r=>r.findings[0].evidenceRefs=[]],['failing result hidden under satisfied',r=>r.verificationResults[0].result='FAIL'],['failed condition disguised as unknown',r=>{r.verificationResults[0].result='FAIL';r.findings[0].status='UNVERIFIED';}],['false summary PASS',r=>r.verdict='FAIL'],['false blocking list',r=>r.blockingFindingIds=['F-CLAIM']],['false unverified list',r=>r.unverifiedRequiredObligationIds=['OB-CLAIM']],['VIOLATED without failing check',r=>r.findings[0].status='VIOLATED'],['evidence path escape',r=>r.evidence[0].path='../elsewhere'],['unknown review field',r=>r.approved=true]
])test('review rejects '+name,()=>{const f=fixture();mut(f.review);reject(()=>validateReviewReport(f.review,reviewOptions(f)));});
test('proper NOT_RUN result is BLOCKED, never PASS',()=>{const f=fixture();Object.assign(f.review.verificationResults[0],{executionStatus:'NOT_RUN',result:'UNKNOWN',evidenceRefs:[]});Object.assign(f.review.findings[0],{status:'UNVERIFIED',evidenceRefs:[]});f.review.unverifiedRequiredObligationIds=['OB-CLAIM'];f.review.verdict='BLOCKED';assert.equal(validateReviewReport(f.review,reviewOptions(f)).verdict,'BLOCKED');});
test('required condition excluded after freeze is BLOCKED',()=>{const f=fixture();f.review.findings[0].status='NOT_APPLICABLE';f.review.findings[0].evidenceRefs=[];f.review.verdict='BLOCKED';assert.equal(validateReviewReport(f.review,reviewOptions(f)).verdict,'BLOCKED');});
test('required violation is FAIL even when other conditions pass',()=>{const f=fixture();f.review.verificationResults[0].result='FAIL';f.review.findings[0].status='VIOLATED';f.review.blockingFindingIds=['F-CLAIM'];f.review.verdict='FAIL';assert.equal(validateReviewReport(f.review,reviewOptions(f)).verdict,'FAIL');});
test('advisory failure remains visible but does not block required success',()=>{const f=fixture();f.constraint.invariants[0].requirementLevel='recommendation';f.constraint.verificationObligations[0].requirementLevel='advisory';f.review.constraintReportDigest=hashJson(f.constraint);f.review.verificationResults[0].result='FAIL';f.review.findings[0].status='VIOLATED';assert.equal(validateReviewReport(f.review,reviewOptions(f)).verdict,'PASS');});
test('candidate paths are unique and sorted',()=>{const f=fixture();f.candidate.files.push(clone(f.candidate.files[0]));reject(()=>validateCandidate(f.candidate));const f2=fixture();f2.candidate.files.unshift({path:'z.txt',digest:f2.candidate.files[0].digest});reject(()=>validateCandidate(f2.candidate));});
test('provider output preserves negative result codes',()=>{assert.equal(providerResult({verdict:'PASS'}).error,null);assert.equal(providerResult({verdict:'FAIL'}).error.code,'GATE_FAILED');assert.equal(providerResult({verdict:'BLOCKED'}).error.code,'MISSING_EVIDENCE');assert.equal(providerResult({verdict:'READY'}).kind,'output');assert.equal(adapterError(new Error('secret')).error.message.includes('secret'),false);});
test('adapter accepts trusted pins and checks raw input',()=>{const f=fixture();assert.equal(reviewForAgs(f,{expectedBindingDigest:hashJson(f.binding),expectedCandidateDigest:hashJson(f.candidate),expectedPolicyDigest:hashJson(f.policy)}).output.verdict,'PASS');});
test('adapter rejects missing context and caller-substituted pins',()=>{const f=fixture();assert.equal(reviewForAgs(f,null).error.code,'BINDING_REQUIRED');assert.equal(reviewForAgs(f,{expectedBindingDigest:'invalid'}).error.code,'INTEGRITY_FAILED');});
test('unknown schema properties are closed, including nested objects',()=>{const f=fixture();f.policy.fakeApproval=true;reject(()=>validateSchema('cs-policy',f.policy));f.candidate.files[0].verified=true;reject(()=>validateSchema('cs-candidate',f.candidate));});
