import test from 'node:test';
import assert from 'node:assert/strict';
import { writeFileSync, mkdirSync, cpSync, symlinkSync, unlinkSync } from 'node:fs';
import path from 'node:path';
import { scratch, fixture, SKILL } from './helpers.mjs';
import { portablePath, canonicalJson, hashJson, hashBytes, readBoundedFile, readArtifact, parseJson, CsError } from '../../skills/cs-engineering/scripts/primitives.mjs';
import { loadPack, checkBundle } from '../../skills/cs-engineering/scripts/core.mjs';
const reject=fn=>assert.throws(fn);
for(const p of ['../secret','/tmp/secret','C:/secret','x\\y','a/./b','a//b','CON','con.txt','NUL.txt','com1.log','x.','x ','a\u0000b','a:b'])test('portable paths reject '+JSON.stringify(p),()=>reject(()=>portablePath(p)));
test('portable path accepts unicode ordinary relative files',()=>assert.deepEqual(portablePath('근거/a-file.json'),['근거','a-file.json']));
test('canonical JSON is key-order stable and array-order sensitive',()=>{assert.equal(hashJson({b:2,a:1}),hashJson({a:1,b:2}));assert.notEqual(hashJson([1,2]),hashJson([2,1]));assert.equal(canonicalJson({z:'한글'}),'{"z":"한글"}');});
for(const [label,value]of[['NaN',NaN],['Infinity',Infinity],['undefined',undefined],['function',()=>0],['Date',new Date()],['BigInt',1n]])test('canonical JSON rejects '+label,()=>reject(()=>canonicalJson(value)));
test('deep and cyclic objects fail boundedly',()=>{let v={};for(let i=0;i<100;i++)v={child:v};reject(()=>canonicalJson(v));const c={};c.self=c;reject(()=>canonicalJson(c));});
test('invalid UTF-8 is rejected rather than replaced',()=>reject(()=>parseJson(Buffer.from([0xff,0xfe]))));
test('raw hashes use file bytes, not parsed JSON',t=>{const root=scratch(t);writeFileSync(path.join(root,'a.json'),'{"a":1}\n');const d=hashBytes(Buffer.from('{"a":1}\n'));readArtifact(root,{path:'a.json',digest:d});writeFileSync(path.join(root,'a.json'),'{ "a": 1 }\n');assert.throws(()=>readArtifact(root,{path:'a.json',digest:d}),e=>e instanceof CsError&&e.code==='INTEGRITY_FAILED');});
test('bounded read rejects directories and oversize files',t=>{const root=scratch(t);mkdirSync(path.join(root,'dir'));reject(()=>readBoundedFile(root,'dir'));writeFileSync(path.join(root,'big'),Buffer.alloc(32));reject(()=>readBoundedFile(root,'big',16));});
test('file symlink is rejected',t=>{const root=scratch(t);mkdirSync(path.join(root,'actual'));writeFileSync(path.join(root,'actual/file'),'data');try{symlinkSync('actual/file',path.join(root,'link'));}catch(error){if(process.platform==='win32'&&['EPERM','EACCES'].includes(error?.code)){t.skip(`Windows file symlink creation unavailable: ${error.code}`);return;}throw error;}reject(()=>readBoundedFile(root,'link'));});
test('intermediate directory symlink or junction is rejected',t=>{const root=scratch(t),actual=path.join(root,'actual'),windows=process.platform==='win32';mkdirSync(actual);writeFileSync(path.join(actual,'file'),'data');symlinkSync(windows?actual:'actual',path.join(root,'dirlink'),windows?'junction':'dir');reject(()=>readBoundedFile(root,'dirlink/file'));});
test('tampered knowledge content fails before use',t=>{const root=scratch(t);cpSync(SKILL,root,{recursive:true});writeFileSync(path.join(root,'references/concurrency.md'),'tampered');reject(()=>loadPack(root));});
for(const file of ['candidate/queue.py','evidence/queue-tests.json','source/request.txt','constraints.json'])test('bundle rejects modified raw '+file,t=>{const root=scratch(t,true),f=fixture();writeFileSync(path.join(root,file),'changed\n');reject(()=>checkBundle({...f,root}));});
test('bundle rejects missing raw evidence',t=>{const root=scratch(t,true),f=fixture();unlinkSync(path.join(root,'evidence/queue-tests.json'));reject(()=>checkBundle({...f,root}));});
