export const SESSION_MESSAGE_PROTOCOL = "1.0.0";
export const SESSION_MESSAGE_MAX_REQUEST_BYTES = 32 * 1024;
export const SESSION_MESSAGE_MAX_RESPONSE_BYTES = 32 * 1024;
export const SESSION_MESSAGE_BODY_MAX_BYTES = 4096;
