import datetime,hashlib,json,pathlib
from runner import ROOT
raw=ROOT/'raw';original=json.loads((raw/'OFFICIAL-RESULT.json').read_text());assert original['officialExecutionAttempts']==1 and original['exitCode']==1
stdout=(raw/'logs/19-validate-official.stdout.log').read_text();assert 'runDepsStatusCheck' in stdout and 'ENOENT' in stdout and 'pnpm.mjs install' in stdout and 'Plugin validation passed:' not in stdout and 'Skill is valid!' not in stdout
pnpm=pathlib.Path('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/pnpm/dist/pnpm.mjs');b=pnpm.read_bytes();lines=b.decode().splitlines();excerpts=[]
for start,end in [(150076,150086),(150686,150696),(253958,253987),(254816,254838),(255202,255225)]:
 excerpts.append(dict(sourceFile=str(pnpm),startLine=start,endLine=end,lines=lines[start-1:end]))
detail=dict(pnpmVersion='11.19.0',implementationSha256=hashlib.sha256(b).hexdigest(),sourceRootConfig=(ROOT/'candidate/pnpm-workspace.yaml').read_text(),excerpts=excerpts,userConfiguration='Not queried or modified',result='Default verify-deps-before-run=install plus absent node_modules caused a pre-script install subprocess. It failed initializing the default store. This is a runner blocker, not an official validator FAIL.')
(raw/'PNPM-BLOCKER-SOURCE.json').write_text(json.dumps(detail,ensure_ascii=False,indent=2)+'\n')
status=dict(schema='AGSOfficialValidationOutcome.v1',status='BLOCKED_PNPM_PRE_SCRIPT_AUTOINSTALL',pnpmCommandAttempts=1,pnpmExitCode=1,officialPluginValidation='NOT_RUN',officialSkillValidation='NOT_RUN',skillDirectoriesNotRun=22,executionAssessment='pnpm source flow and captured error stack place the failure before the package script; no official result was emitted. No per-child syscall trace was collected.',unexpectedInstallAttempt=True,completedDependencyInstallObserved=False,globalStoreWriteAttempt=True,globalStoreWriteResult='ENOENT observed; successful creation not observed. Default global directories were not queried or repaired.',policyDeviation='The intended no-install invocation triggered an implicit pnpm install. Preserve the attempt and failure; do not relabel PASS or claim zero install attempts.',originalRunReportPreserved='OFFICIAL-RESULT.json retains the original CLI FAIL/exit1. Its officialExecutionAttempts field counts the attempted wrapper invocation, not successful or started official Python validators.',candidateHead=original['candidateHead'],candidateTree=original['candidateTree'],sourcePrePostByteExact=True,sourceCleanPrePost=True,supplierCommit=original['supplierCommit'],supplierBytesExact=True,compatibility='STATIC_KEY_COMPATIBLE only; full official validation remains NOT_RUN',correctedRetryCount=0,fullTestsBuildRuntimeRun=0,fixtureR1R2Integrated=False,mainTagReleaseInstallPush='No direct main/tag/release/host-install/push operation; unexpected dependency-install attempt disclosed above',nextOptions=[dict(option='Use an isolated ready dependency tree',scope='Parent must approve a changed dependency/store input and verify its lock/state; copy only into this disposable checkout, never share a mutable original node_modules. No user store repair.'),dict(option='Use a child-process pnpm dependency-precheck setting',scope='Parent must review exact pnpm runner env/flag and distinction from unchanged official validation. No global/user config or validator relaxation; do not apply automatically.'),dict(option='Keep the release gate blocked',scope='Wait for an authorized changed-input official run; do not substitute old tests or direct Python invocation as pnpm validate:official PASS.')],preparedAtUtc=datetime.datetime.now(datetime.timezone.utc).isoformat())
(raw/'ANNOTATED-RESULT.json').write_text(json.dumps(status,ensure_ascii=False,indent=2)+'\n');print(json.dumps(status,ensure_ascii=False,indent=2))
