#!/usr/bin/env bash
# Temporary recovery only. Import generated bytes, freeze a new final pin,
# then run full CI, official validation and the real Claude-host delta.
set -euo pipefail
test "$(uname -s)" = Linux
out="${RUNNER_TEMP:?}/cs281-generation"
mkdir -p "$out"
exec > >(tee "$out/full.log") 2>&1
printf 'NOT_FULL_QA\n' > "$out/STATUS.txt"
finish() {
  local command_code=$? artifact_code=0 code
  trap - EXIT
  set +e
  {
    git rev-parse HEAD HEAD^{tree}
    git status --porcelain=v1
    git diff --stat
  } > "$out/environment-after.txt"
  git diff --binary > "$out/generated.patch"
  git diff --name-only > "$out/changed-paths.txt"
  # Explicit generation roots preserve additions and full shipped bytes.
  tar -czf "$out/generated-bytes.tar.gz" mcp-server/dist runtime claude-plugin || artifact_code=$?
  find mcp-server/dist runtime claude-plugin -type f -print0 | sort -z | xargs -0 sha256sum > "$out/generated-files.sha256" || artifact_code=$?
  printf '%s\n' "$command_code" > "$out/command-exit-code.txt"
  code=$command_code
  if [ "$code" -eq 0 ]; then code=$artifact_code; fi
  if [ "$code" -eq 0 ]; then
    printf 'GENERATED_BYTES_READY_NOT_FULL_QA\n' > "$out/STATUS.txt"
  else
    printf 'FAILED_NOT_FULL_QA\n' > "$out/STATUS.txt"
  fi
  printf '%s\n' "$code" > "$out/script-exit-code.txt"
  printf '%s\n' "$artifact_code" > "$out/artifact-exit-code.txt"
  # full.log is still open here; the upload artifact supplies its final bytes.
  (cd "$out" && find . -type f ! -name 'SHA256SUMS*' ! -name full.log -print0 | sort -z | xargs -0 sha256sum > SHA256SUMS.tmp && mv SHA256SUMS.tmp SHA256SUMS) || artifact_code=$?
  code=$command_code
  if [ "$code" -eq 0 ]; then code=$artifact_code; fi
  # On checksum failure these final records invalidate any incomplete sums.
  if [ "$code" -ne 0 ]; then printf 'FAILED_NOT_FULL_QA\n' > "$out/STATUS.txt"; fi
  printf '%s\n' "$artifact_code" > "$out/artifact-exit-code.txt"
  printf '%s\n' "$code" > "$out/script-exit-code.txt"
  exit "$code"
}
trap finish EXIT
{
  date -u +%FT%TZ
  uname -a
  node --version
  corepack --version
  git rev-parse HEAD HEAD^{tree}
  git status --porcelain=v1
  printf 'run=%s attempt=%s ref=%s\n' "${GITHUB_RUN_ID:-}" "${GITHUB_RUN_ATTEMPT:-}" "${GITHUB_REF:-}"
} > "$out/environment-before.txt"
printf 'label\texit_code\tcommand\n' > "$out/commands.tsv"
record() {
  local label="$1" code
  shift
  printf '\nCOMMAND %s:' "$label"
  printf ' %q' "$@"
  printf '\n'
  set +e
  timeout --signal=TERM --kill-after=30s 600s "$@" 2>&1 | tee "$out/$label.log"
  code=${PIPESTATUS[0]}
  set -e
  printf '%s\t%s\t' "$label" "$code" >> "$out/commands.tsv"
  printf '%q ' "$@" >> "$out/commands.tsv"
  printf '\n' >> "$out/commands.tsv"
  return "$code"
}
record corepack-enable corepack enable
record pnpm-pin corepack prepare pnpm@11.19.0 --activate
pnpm --version | tee "$out/pnpm-version.txt"
test "$(pnpm --version)" = 11.19.0
node -e 'if (Number(process.versions.node.split(".")[0]) !== 24) process.exit(1)'
node -e 'const r = JSON.parse(require("node:fs").readFileSync("release/version.json", "utf8")); if (r.version !== "2.8.1" || r.status !== "candidate" || r.publicVersion !== "2.8.0") process.exit(1)'
record frozen-install pnpm install --frozen-lockfile
# Record every cold check before any generation; expected stale failures remain
# raw nonzero receipts, never relabelled PASS.
record cold-bundle pnpm bundle:check || :
record cold-claude-drift pnpm claude:drift || :
record cold-context pnpm skills:context-check || :
record generate-runtime pnpm build
record generate-claude pnpm claude:build
record generated-claude-check pnpm claude:check
